theme = "autumn_night"

[editor]
line-number = "relative"
mouse = true
true-color = true
cursorline = true
completion-replace = true
bufferline = "always"
auto-pairs = false  

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true # Ignore hidden files 

[editor.lsp]
auto-signature-help = false
display-messages = true
